CREATE TABLE Game (
    game_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_title VARCHAR2(100) NOT NULL
);

CREATE TABLE Player (
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    address VARCHAR2(200),
    postal_code VARCHAR2(10),
    province VARCHAR2(30),
    phone_number VARCHAR2(20)
);

CREATE TABLE PlayerAndGame (
    player_game_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id NUMBER NOT NULL,
    player_id NUMBER NOT NULL,
    playing_date DATE,
    score NUMBER,
    FOREIGN KEY (game_id) REFERENCES Game(game_id),
    FOREIGN KEY (player_id) REFERENCES Player(player_id)
);
